[package]
name = "brug-macros"
description = "the proc macro(s) for the brug crate"
version = "0.1.1"
edition = "2021"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2", features = ["full"] }